name: Python

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install --all-extras
      - run: make lint
      - run: make test
      - run: poetry run make test_integration
